#include "mapSetCommon.dl"

//id, operation, value
.decl edgesOp(e: symbol, y: symbol, x: symbol, z: symbol)

.input vis

.decl laterVisOpEdges(e: symbol)
laterVisOpEdges(e) :- edgesOp(e, _, x, z), edgesOp(p, _, x, z), visible(e, p), e!=p.

.decl lastVisibleOpEdges(e: symbol)
lastVisibleOpEdges(e) :- edgesOp(e, _, _, _), !laterVisOpEdges(e).


.decl edgesState(x: symbol, z: symbol)
edgesState(x, z) :- edgesOp(e, "add", x, z), lastVisibleOpEdges(e).
.output edgesState

